### ISSUE TITLE
Change dots for underscores in function names

### ISSUE THREAD

**Issue by Bisaloo** [groundhogR/groundhogR#26]
It's considered bad practice to use dots in functions names other than to indicate S3 dispatch (which is not the case here). Some repositories, such as [Bioconductor](https://www.bioconductor.org/developers/package-guidelines/), which is widely used in bioinformatics, even forbid it entirely:

> Function names should be camel case or utilize the underscore _ and not have a dot . which indicates S3 dispatch.

I think it would make sense to rename functions such as `groundhog.library()` to `groundhog_library()`.

**Comment by urisohn** [comment]
I am open to it but i don't think convention is followed.
There are common functions I use:
read.csv()
install.packages()
pwr.t.test()
predict.lm()
new.data()
available.packages()

I looked up the link you sent and noticed that the very first function after Bioconductor recommends not using periods, involves a period..
![image](https://user-images.githubusercontent.com/56013245/80366521-b3672580-8889-11ea-8e12-55fa9305c08a.png)

am i missing something? seems like the ship sailed on that attempt to standardize. 
I don't feel super strongly, but if people don't really follow that, and aesthetically i prefer the period.

**Comment by Bisaloo** [comment]
Yes, this is one of the many inconsistencies in R due by historical reasons. So I prefer underscores but as you said, this ship has kind of sailed already so I don't feel super strongly either.

As a side note, `predict.lm()` is not a super good example here because it is an example of S3 dispatch. Typically, you would not call `predict.lm()` directly but instead call `predict()` on a `lm` object. All you other examples are totally correct.
