### ISSUE TITLE
Add specific HTTP header for groundhogR?

### ISSUE THREAD

**Issue by Bisaloo** [groundhogR/groundhogR#27]
So the servers (CRAN & MRAN) know that the request comes from groundhogR.

Currently, they see requests from either `"RStudio Desktop (1.2.5019); R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu)"` or `"R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu)"`.

**Comment by urisohn** [comment]
sorry, i don't understand

**Comment by Bisaloo** [comment]
When you connect to a website, the program you use for this sends a User-Agent. It's kind of a business card declining its identity.

For example, here you can see how your web browser presents itself to every website you visit: https://www.whatismybrowser.com/detect/what-is-my-user-agent.

Right now, we are connecting to CRAN and MRAN by announcing we are using R (and possibly RStudio). It might be nice for them to have more information and know that those are not direct requests from users but they are done under the hood by groundhogR.

**Comment by urisohn** [comment]
If we are talking about what groundhogR does from within R as a user, I am not sure i see why. 
or put another way, when i install a package with install.pacakges() what HTTP headers are sent? I would emulate their approach to this.

**Comment by Bisaloo** [comment]
For the user, it doesn't change anything.

It's only useful for MRAN and CRAN (and possibly us). This way, they know that these requests come from us. They can contact us if something is wrong with how groundhogR behaves.

`install.packages()` is slightly different in my opinion because it signals the user explicit intent to download and install the package whereas `groundhog.library()` kind of does it as a side effect.

**Comment by urisohn** [comment]
ok, let's do this. let's wait till i do the updates though.

**Comment by Bisaloo** [comment]
How does `paste0("groundhogR R package version ", utils::packageVersion("groundhogR"), " running on R ", get.rversion())` sound?

**Comment by Bisaloo** [comment]
I hadn't thought about this but this is only feasible on most recent R versions so I'm going to close this issue for now.
