### ISSUE TITLE
Workaround for source and Linux

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#29]
Line 50 in install.snowball.R reads:
![image](https://user-images.githubusercontent.com/56013245/80607731-21e8e680-8a36-11ea-909f-7bd508d93051.png)
That seems like a solution rather than workaround, just confirming you are OK leaving that as is in the final version

**Comment by Bisaloo** [comment]
I pushed a better solution in https://github.com/groundhogR/groundhogR/commit/faf4b2d77f426b069a0ac1fdc15b765fa097be75 so I think we can keep it this way now.
