### ISSUE TITLE
type=square when downloading .rds

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#30]
![image](https://user-images.githubusercontent.com/56013245/80609354-434ad200-8a38-11ea-90cf-c9bb9198dc23.png)
why is there a 'square' for type, and do you know the origin of that message?
my guess is that we are not responsible for it, but figured i  check

**Comment by Bisaloo** [comment]
Here is what I see:

> trying URL 'https://groundhogR.com/cran.times.rds'
Content type 'unknown' length 304480 bytes (297 KB)
==================================================
downloaded 297 KB

Are these messages useful anyways or should they be removed?

**Comment by urisohn** [comment]
You mean remove using quiet =TRUE in download.file?
I think it is good for users to know an .rds file is being downloaded
We could replace it with our own message1() message, but maybe it is not worth it. Unless you think otherwise i would leave as is

**Comment by Bisaloo** [comment]
> You mean remove using quiet =TRUE in download.file?

Yes, that's what I meant.

I think they're not super useful since the user doesn't know what this `cran.times.rds` is or why it needs to be downloaded.

But I don't have strong opinions on this so I'm happy to follow your choice.

**Comment by urisohn** [comment]
i would keep it, i think all info provided can be useful for debugging or for users to google when they run into a problem.

my intuition the problem originates in calling a file on the web which does not have a conent type header. I don;t know how to fix that and seems unimportant. 
so, i think this would be fixed on http://groundhogr.com but dont know how.

if you do, let me know and i will take carte of it
if you don't know, lets leave as is

**Comment by Bisaloo** [comment]
It depends on the software on your server. With apache, here is what I have in `.htaccess`:

```sh
# Add MIME support
AddType image/svg+xml svg svgz
AddEncoding gzip svgz
```

But I'm not entirely sure of what you use or if you have access to these settings.

**Comment by urisohn** [comment]
thanks, that worked.
