### ISSUE TITLE
Is msg.plot() still needed?

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#32]
I wrote msg.plot() because I could not get the verbose output from the source installation to not show, and it was so much text that any feedback trhough the console got lost.
But it seems you did manage to turn that output off, and with the default parameter of quiet=TRUE in goundhog.library() there is no verbose reporting of install from source.

I am tempted to get rid of msg.plot() and put the estimated ending time within the regular console.

The only argument against it I see is that the install from source output can be useful if you are getting an error.  is it possible to capture it and output it if an error occurs? If not, we could have the message() tell the user, when the installation of source fails, to choose quiet=FALSE if they want to figure out what's wrong.

I guess i lean towards the following, either
1) we change the default to quiet=FALSE and keep msg.plot()
2) we keep the default with quiet=TRUE, get rid of msg.plot()

**Comment by Bisaloo** [comment]
> we keep the default with quiet=TRUE, get rid of msg.plot()

I'm not a big fan of cat1.plot() so I'm happy to remove it. I'll have a look at how we can capture the output and return it in case of error. It sounds doable.

**Comment by Bisaloo** [comment]
The output for each installed package is now stored in `~/groundhogR/logs/`. I'm not sure what we should do with it then?

- print a message saying that users can find the logs in this folder
- print the error message if `now_installed` returns `FALSE`

**Comment by urisohn** [comment]
What if, whe when installing unsuccesfully from source we say 
message1("The attempt to install from source was unsuccesful. Here is the output that was generated when installation was attempted:")
and then just print the relevant log?
