### ISSUE TITLE
message2() when needed only

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#33]
I created message2() so that users would know who was giving them the messages they were reading.
A lot of times it seems a bit redundant.
Was thinking that it would be better if message() was shown only when the last message shown in the console was not message1()

So you would have 
message2()
message1()
...
message1()

...some other output shown...
message2()

This just a luxury to make it smoother. 
How hard is it you think to keep track of whether the last thing to show up int eh console was output fro this package (i.e., a message1())

if it is hard, just close this issue without doing anything

**Comment by Bisaloo** [comment]
It sounds hard. I believe recent changes in R 4.0.0 just made this kind of things possible but it's still really hard. We can keep it in mind for a possible future though.

**Comment by urisohn** [comment]
ok, i hand coded this feature about 80%, just working through likely scenarios, reducing usage of message2()

**Comment by urisohn** [comment]
ok to close
