### ISSUE TITLE
Questions about setting folder for groundhogR to use

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#35]
ref: get.groundhogR.folder()

I edited a bit the text when people are prompted to enter the folder they want to use.

1) But i don't know how to unset the value so it is hard for me to test it (I am not prompted)
So it is possible I introduced a typo-based bug there.

2) If possible, i wouldl ike to spell our the home folder for them, so that instead of seeing "~" they would see "c:/documents and settings/uri/....'

3) If someone ttries to set their own path, are there permission issues? For example, say they create c:/dropbox/groundhogR, will R be allowed to create that folder and save to it (allowed by the operating system i mean)

**Comment by Bisaloo** [comment]
> But i don't know how to unset the value so it is hard for me to test it (I am not prompted)
So it is possible I introduced a typo-based bug there.

You need manually edit your `.Renviron` file that should be your in home.

> If possible, i wouldl ike to spell our the home folder for them, so that instead of seeing "~" they would see "c:/documents and settings/uri/....'

I'll look into this.

> If someone ttries to set their own path, are there permission issues? For example, say they create c:/dropbox/groundhogR, will R be allowed to create that folder and save to it (allowed by the operating system i mean)

R (and therefore groundhogR) should have the same permissions as the user running it.

**Comment by urisohn** [comment]
yes.
