### ISSUE TITLE
failure to install from source via groundhog.library() but install.packages() works

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#37]
`  groundhog.library("stringi","2020-02-11",quiet=F)`
leads to this error message

![image](https://user-images.githubusercontent.com/56013245/81156952-c6af7a80-8f86-11ea-822b-18b43234049a.png)

but if i try to install the same .tar.gz file like this:
`    install.packages(file.choose(), repos=NULL)`
it works

I even copied the entire key line and run it on its own, and it works. That is, if i run 
`    install.packages(tarball.path, type = "source", lib = lib, quiet = quiet.install, dependencies = FALSE, repos = NULL, INSTALL_opts = "--no-staged-install")
`

putting vales to tarballpath., lib, quiet, it works

only within the function install.source(), called in turn from groundhog.library() does is give that errror about 'sh'

**Comment by Bisaloo** [comment]
This is going to be difficult to debug since it's a windows specific issue and I don't have access to a windows computer during lockdown.

Could you try installing it with `install.source()` please?

**Comment by urisohn** [comment]
I understand. Will try that next.
It's also a package that takes >5 minutes to install, not a fun thing to debug

**Comment by urisohn** [comment]
what's an easy way to call install.source()?
It depends on other functions in the package, so if i just run it is missing functions
Exporting it from the package?

**Comment by urisohn** [comment]
my intuition is that when called from within the package, RTools (needed for some packages from source) are not available or not available in the same way than when called from the environment directly.

**Comment by Bisaloo** [comment]
yes, this sounds like a RTools issue indeed.

you can use `groundhogr:::install_source()` to call unexported functions.

**Comment by urisohn** [comment]
thanks. same error
Warning in system("sh ./configure.win") : 'sh' not found

**Comment by urisohn** [comment]
i tried a different computer, and it runs fine. 
Let me try a few more before you spend any (more) time on it

**Comment by Bisaloo** [comment]
It might be related to your RTools issue some time ago. Your fix might have fixed it for you but for some reason, packages still can't find it

**Comment by urisohn** [comment]
yes, that's my hope.
i have 3 kids, they will all get R, RStudio and groundhogR in their machines today... : )
I am confident, but not certain, the problem is local and ignorable.

**Comment by Bisaloo** [comment]
Did you manage to reproduce this issue of should this considered fixed?

**Comment by urisohn** [comment]
let's wait. i stopped running tests when you uncovered the linkingTo problem.

**Comment by urisohn** [comment]
almost completed rebuilding the cran.toc.rds but not yet, and only when I do that i will continue with testing.
