### ISSUE TITLE
stop2

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#38]
Any problem with using this to avoid an 'error' warning when there is no error?
```
stop2=function(msg){
     message2(msg)
     opt <- options(show.error.messages=FALSE)
     on.exit(options(opt))
     stop(msg)
     }
 
```

I am using it when setting the folder, i do want the process to stop if they want to set the folder themsevles, but it should not read 'error'

**Comment by urisohn** [comment]
i wasn't sure how to turn it into a function, but you will see how i use it 
get.groundhogr.folder.R if they don't type 'yes' or ENTER

**Comment by Bisaloo** [comment]
There is an easier and better way: adding `call. = FALSE` to `stop()` calls.

**Comment by Bisaloo** [comment]
Well, it still displays `error:` but it doesn't mess up with debugging. I'll look how we can remove the `error;`

**Comment by Bisaloo** [comment]
My issue with your approach is that everything happens as if no error occurred. I don't think this does make sense. If we feel the need to put `stop()`, then it means an error occurred and we should inform the user of this.

Maybe you are looking for early returns, such as:

https://github.com/ropensci/lightr/blob/11548e8047e7eb26c0d30ba8620e9edee76f4cdf/R/get_spec.R#L73-L75

**Comment by urisohn** [comment]
I don't want to replace real stop() with stop2() . So if there is a missing file or argument, i do watn stop. So maybe it is only for the situation where they say "no" to the default folder. My first instict was an early return but it generated an error, however, i think the function can be stlightly modified to bypass that. I hope to be done tomorrow AM with the whole review and you can look at it.
