### ISSUE TITLE
own repository?

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#39]
I don't think i want to share the package with install from github,  requriing devtools is a deal breaker. But i think it is relatively easy to structrure a website to act as a repository, so if we put the source file on groundhogr.com, i think it could go out to beta testers who woudl install like this

install.packages("groundhogR", repos='groundhogr.com")

Is that right? 
If it is possible, is there an obvious counter?

I am worried that I have stumbled on several issues so it may make sense to release a limited edition before making it truly public.

**Comment by Bisaloo** [comment]
Several points:

- you don't need devtools to install from GitHub, just remotes.

- the easiest way to distribute a package without CRAN or GitHub is to distribute the tarball and then tell users to install it with `install.packages("groundhogr.tar.gz", repos = NULL)`. It's also possible (but not really good practice) to provide a script that does all this so users just have to run `source("url_to_script_to_install_groundhogR")`

- it is possible to make a clean, full-fledged CRAN-like, as you suggest with the [drat package](https://github.com/eddelbuettel/drat) but it's probably a bit more work. I've never really look into it. I just knows it exists, it's developed by a reliable developer and it's **supposed to be** easy to manage.

**Comment by urisohn** [comment]
ok. good points.
Maybe this solutio is the easiest to achieve: put the tar.gz on groundhogR.com

install.packages("http://groundhogR.com/1.0.0.tar.gz", repos=NULL)

Just tested it with another package and it run smoothly.
