### ISSUE TITLE
toc() shows row number

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#43]
![image](https://user-images.githubusercontent.com/56013245/81310325-3ce5d700-9084-11ea-8b59-70039b5f03fa.png)

probably best to skip that 1st columns, right?

**Comment by Bisaloo** [comment]
This should probably be fixed server side first. `cran.toc` has the same issue.

**Comment by urisohn** [comment]
ah, you mean the .rds file should not have row names or something like that

**Comment by Bisaloo** [comment]
Yes, I think so, it's doesn't have any relevant meaning for the user so it's just confusing.

The easiest way to reset rownames is: `rownames(obj) <- NULL`

**Comment by Bisaloo** [comment]
see also https://github.com/groundhogR/groundhogR-server/issues/1.
