### ISSUE TITLE
Can't find available dependency

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#44]
library(groundhogR)
groundhog.library("rio","2017-01-01",quiet.install = F)
groundhog.library("BH","2017-01-01")
groundhog.library("rio","2017-01-01",quiet.install=F)

Leads to this error:
ERROR: dependency 'BH' is not available for package 'xml2'

**Comment by urisohn** [comment]
Including BH in the current.dep() it runs.
But i don't understand why get.all.dependencies() did not find it. Wonder if there is a way to discover toubling dependencies like this one

**Comment by Bisaloo** [comment]
`get.all.dependencies()` didn't not find it because it's not in either `Imports` or `Depends` but in `LinkingTo`.

Maybe this was the issue with Rcpp as well all along.

**Comment by urisohn** [comment]
The issue with Rcpp was different, because it woudl try to install Rcpp and fail.
Seems like the only option is to recrate crant.toc.rds from scratch, adding the linkto field.

**Comment by urisohn** [comment]
this must have not happened before becauase i was using a computer which I use for R all the time, o BH was installed in the library, when I tested it in a new computer, it became detectable.

I saved all the R Code I use to create the cran.toc from scratch, am re-running now. This may be accomplished by tomorrow.

**Comment by urisohn** [comment]
For current packages this is eas to do with available.pacakge()
my approach is downloading all tarballs and processing their DESCRIPTION files.
If you know of a more efficient way let me know.

Te only alterantive i can think of, if there are sufficiently few linking-to packages, is to include all of them in the current,dep by default

**Comment by urisohn** [comment]
OK, there are 100
```
ap=data.frame(available.packages(),stringsAsFactors = F)
clean.dep=function(dep)
  {
          dep=as.character(dep)
          if (length(dep)==0) return("")      #return() if no dependencie
          dep=strsplit(dep,",")[[1]]          #Split array by ,
          dep=gsub("\\s*\\([^\\)]+\\)","",dep)#Kill the parenthense 
          dep=gsub("\n", "", dep)             #Kill \n
          dep=trimws(dep)                     #Trim
          dep=dep[dep!="R"]                   #Don't include R as dependency
          dep=dep[dep!=""]                    #Drop empty dependencies
          dep=paste0(dep,collapse=",")        #Concatenate
          return(dep)
  }

link.all1=data.frame(table(ap$LinkingTo),stringsAsFactors = F)
link.all2=c()
for (k in 1:nrow(link.all1)) link.all2=c(link.all2, clean.dep(link.all1[k,1]))
link.all3=paste0(link.all2,collapse=",")
link.all4=strsplit(link.all3[1],",")[[1]]
link.all5=unique(link.all4)
```

**Comment by Bisaloo** [comment]
> my approach is downloading all tarballs and processing their DESCRIPTION files.
If you know of a more efficient way let me know.

Another idea would be to run `available.packages()` on all dates in the MRAN archive. Not sure it would be much more efficient though

**Comment by urisohn** [comment]
i have finished updating the cran.toc.rds with the new field.

**Comment by urisohn** [comment]
ok, i made the small edits to the get.dependencies() function and generated errors, sorry.
My guess is that it is not getting the updated cran.toc.rds for the test, but i don't know how to update that. sorry

**Comment by Bisaloo** [comment]
I fixed some issues. The remaining problem is that the published column is not a `Date` anymore. I think you need to change this server side.

**Comment by urisohn** [comment]
ok. on it.

**Comment by urisohn** [comment]
ok. should be fine now.

**Comment by Bisaloo** [comment]
The `Published` column now contains some `NA` that are not supposed to be here. Could you check please?

**Comment by urisohn** [comment]
on it

**Comment by urisohn** [comment]
ok, so that you can work without a problem i just dropped them for now, will go back and see when the NA's were added. There are several dates in improper formats in earlier DESCRIPTION files, i must have missed some cases. Sorry.

so, cran.toc.rds on the groundhogr.com server already does not have NAs in $Published

**Comment by urisohn** [comment]
ok, added back the (many of) the previously missing dates.
It's just for completeness as they are from before 2005 anyway
sorry for all the hiccups.

**Comment by Bisaloo** [comment]
This is fixed for me with the latest version. Feel free to close this issue once you've verified it works on your end as well.
