### ISSUE TITLE
repos=NULL in install.source()

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#46]
Doesn't install.packages(...,repos=NULL) also only work for R-3.2.0? I think you changed it for available.packages() but for install.source() we still have that , right? 
That won't work on 3.1 or 3.0 right?

**Comment by Bisaloo** [comment]
No, it's fine, the `repos` argument has been in `install.packages()` since its creation more than 16 years ago. It was added to `available.packages()` in R 3.2 precisely to match the behaviour to `install.packages()`.
