### ISSUE TITLE
Cannot run offline

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#51]
When trying to run groundhog.library() offline, it tries to load from cran, and it cannot, and fails, not running.
More generally, calling on library(groundhog) appears to have a delay, what gets executed when the pacakge is loaded? Is is posisble to make that smoother?

>   library(groundhog)
Warning: unable to access index for repository https://cran.r-project.org/src/contrib:
  cannot open URL 'https://cran.r-project.org/src/contrib/PACKAGES'
Error: package or namespace load failed for ‘groundhog’:
 .onLoad failed in loadNamespace() for 'groundhog', details:
  call: `$<-.data.frame`(`*tmp*`, "pkg_vrs", value = "_")
  error: replacement has 1 row, data has 0

**Comment by Bisaloo** [comment]
Should be fixed by https://github.com/groundhogR/groundhogR/commit/2f96b4369f7ab52724a59b97c08e1578afe944b1
