### ISSUE TITLE
Consider copying startup::restart()

### ISSUE THREAD

**Issue by Bisaloo** [groundhogR/groundhogR#7]
https://github.com/HenrikBengtsson/startup

It currently doesn't work with RStudio though but we should keep watching it.

The code can be copied in groundhogR since it's LGPL but it would be nice to contact the author if we do so.

**Comment by urisohn** [comment]
is this to avoid doing shift-ctrol-f10?

**Comment by Bisaloo** [comment]
> is this to avoid doing shift-ctrol-f10?

Not really since it doesn't work on RStudio at the moment. It would be more like an alternative for users who don't use RStudio (since shift+ctrl+f10 is specific to RStudio).

**Comment by urisohn** [comment]
ah, ok, so the message would be conditional, if using R-Studio prest ctl-sh-f10.
if not, it would prompt a restart throgh this code.
Right?

**Comment by Bisaloo** [comment]
Yes, that could be a nice option to combine this with #3

**Comment by Bisaloo** [comment]
I'm curious about how you see this without #3. Always try to restart programmatically and print the message if it doesn't work?

**Comment by urisohn** [comment]
i would close this. let's not add this functionality, adds a lot of code for a very minor convenience. users who opt-out of R Studio will have no problem re-starting their R sessions
